spring:
  datasource:
    name: test
    url: jdbc:mysql://172.18.3.134:3306/test_wch
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    cluster:
      nodes:
      - redis01.cootel.com:9000
      - redis02.cootel.com:9001
      - redis03.cootel.com:9002
      - redis04.cootel.com:9003
      - redis05.cootel.com:9004
      - redis06.cootel.com:9005